### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by Epi-NMT** [VeloDC/D-SAM_public#1]
Thanks for your implementation. 
Can you write a short instruction that tell us how to reproduce the result on PACS dataset?
Thank you very much.

**Comment by Epi-NMT** [comment]
Because when I run the main.py, it requires job_name.
I don't have any clue about that job_name.

**Comment by VeloDC** [comment]
Dear keyu07,
Thanks for your interest, The README is updated with a description on how to replicate results on PACS using AlexNet.
The job_name is the name of the job, it is needed to create folders for saving logs and checkpoints. You can use anything you like for that argument.
Let me know if you have other issues with the code

**Comment by Epi-NMT** [comment]
Sorry for the late reply and appreciate for you help.
I just get it done and start training.
