### ISSUE TITLE
Office-Home train-val split

### ISSUE THREAD

**Issue by Epi-NMT** [VeloDC/D-SAM_public#2]
I try to run the Office-Home experiment on AlexNet. I see that you have fixed train-val split in Office-Home.py. So could you provide the method how you split train and validation set, or do you have any files that contain those information.

**Comment by VeloDC** [comment]
The splits are randomly generated once. Randomness depends on the output of os.listdir, which is based on the FileSystem. Once the symlinks are created, it will always use the same splits. The logic is defined in [this function](https://github.com/VeloDC/D-SAM_public/blob/master/datasets/OfficeHome.py#L19).

If you need deterministic splits (e.g. if you run the code on different workstations), you can sort the output of os.listdir with `sorted(os.listdir(...))`

**Comment by Epi-NMT** [comment]
> The splits are randomly generated once. Randomness depends on the output of os.listdir, which is based on the FileSystem. Once the symlinks are created, it will always use the same splits. The logic is defined in [this function](https://github.com/VeloDC/D-SAM_public/blob/master/datasets/OfficeHome.py#L19).
> 
> If you need deterministic splits (e.g. if you run the code on different workstations), you can sort the output of os.listdir with `sorted(os.listdir(...))`

Thank you for that.
